### ISSUE TITLE
Nie udało się wczytać interfejsu konfiguracji: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by kowalczykrafal** [Antoni-Czaplicki/vulcan-for-hassio#39]
Wersja HA: 2023.03
Nie udało się wczytać interfejsu konfiguracji: 500 Internal Server Error Server got itself in trouble

**Comment by tomekswx** [comment]
Ja mam w logach po upgrade do 2023.3:

Unable to install package vulcan-api==2.2.1: ERROR: Cannot install vulcan-api==2.2.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by Antoni-Czaplicki** [comment]
Spróbuj usunąć i dodać integrację ponownie

**Comment by tomekswx** [comment]
Niestety teraz mam komunikat jak kolega kowalczykrafal

**Comment by andrzejf1994** [comment]
Również mam ten sam komunikat po usunięciu i próbie ponownego dodania integracji.

**Comment by Antoni-Czaplicki** [comment]
Problem był spowodowany przez inne wersje biblioteki API w integracji wbudowanej i tej customowej z tego repozytorium. Naprawione w 0.14.2

**Comment by mariuszxeno** [comment]
Ale moja używana wersja to 0.14.1 i problem jest.
